### ISSUE TITLE
successful use with ReadTheDocs.org

### ISSUE THREAD

**Issue by Ken-B** [mitya57/python-markdown-math#11]
Not an issue, just a big thank you that your markdown extension works on readthedocs. I've described my setup in an [issue](https://github.com/mkdocs/mkdocs/issues/253#issuecomment-174762734) over there. This is just for cross reference.

**Comment by mitya57** [comment]
Great! You probably meant mkdocs, not readthedocs :)

**Comment by Ken-B** [comment]
No, no, I meant readthedocs.org, the free doc hosting service.
They use mkdocs underneath of course.

**Comment by mitya57** [comment]
Ah, alright then.
