### ISSUE TITLE
Support pandoc-eqnos like equation numbers

### ISSUE THREAD

**Issue by davidanthoff** [mitya57/python-markdown-math#12]
It would be great if one could use equation numbers like in https://github.com/tomduck/pandoc-eqnos. My sense is that this syntax might eventually also be adopted by pandoc.

**Comment by mitya57** [comment]
Hi @davidanthoff! I think you can use the standard LaTeX-like syntax for numbering equations. See [MathJax documentation](http://docs.mathjax.org/en/latest/tex.html#automatic-equation-numbering) for details.

**Comment by davidanthoff** [comment]
Ok, thanks!
