### ISSUE TITLE
Can you provide more details in documentation?

### ISSUE THREAD

**Issue by weasteam** [mitya57/python-markdown-math#14]
I installed the package via `sudo pip install python-markdown-math` in Mac and run the markdown via `html = markdown.markdown(text,extensions=['markdown.extensions.extra','markdown.extensions.mdx_math'])`

Got the error bellow:

```
ImportError: Failed loading extension 'markdown.extensions.mdx_math' from 'markdown.extensions.mdx_math', 'markdown.extensions.markdown.extensions.mdx_math' or 'mdx_markdown.extensions.mdx_math'
```

I am very much appreciated if you can provide more details in installation.

**Comment by mitya57** [comment]
You need to use just `mdx_math` instead of `markdown.extension.mdx_math` (the latter is for built-in extensions).

I have updated the [Usage section in the README](https://github.com/mitya57/python-markdown-math#usage) now.
