### ISSUE TITLE
Failed loading extension 'mdx_math'

### ISSUE THREAD

**Issue by weasteam** [mitya57/python-markdown-math#17]
```
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import markdown
>>> md = markdown.Markdown(extensions=['mdx_math'])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/Library/Python/2.7/site-packages/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/Library/Python/2.7/site-packages/markdown/__init__.py", line 264, in build_extension
    module = importlib.import_module(module_name_old_style)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Failed loading extension 'mdx_math' from 'mdx_math', 'markdown.extensions.mdx_math' or 'mdx_mdx_math'
```

**Comment by mitya57** [comment]
How did you install mdx_math? Where is the installed file located?

**Comment by weasteam** [comment]
`pip install python-markdown-math`
 I am not sure where did the file install.

**Comment by mitya57** [comment]
Does `pip` use the same Python version as your console above?

Can you run `pip show -f python-markdown-math` and paste the output?

**Comment by weasteam** [comment]
```
pip show -f python-markdown-math

Name: python-markdown-math
Version: 0.2
Summary: Math extension for Python-Markdown
Home-page: https://github.com/mitya57/python-markdown-math
Author: Dmitry Shachnev
Author-email: mitya57@gmail.com
License: BSD
Location: /usr/local/lib/python3.5/site-packages
Requires: 
Files:
  __pycache__/mdx_math.cpython-35.pyc
  mdx_math.py
  python_markdown_math-0.2-py3.5.egg-info/PKG-INFO
  python_markdown_math-0.2-py3.5.egg-info/SOURCES.txt
  python_markdown_math-0.2-py3.5.egg-info/dependency_links.txt
  python_markdown_math-0.2-py3.5.egg-info/top_level.txt
```
It looks like it was installed to python3.5. Thanks, I think I know the problem.

I should do `pip2 install python-markdown-math`. 

You can close the issue. Thanks a lot!

**Comment by shuivin** [comment]
I has the same issue  in mkdocs, what should i do?

markdown_extensions: # https://python-markdown.github.io/extensions/
        - mdx_mat # https://github.com/mitya57/python-markdown-math
            enable_dollar_delimiter: True
use ` mkdocs build`
```
ERROR    -  Config value: 'markdown_extensions'. Error: Failed loading extension "mdx_mat".
Aborted with 1 Configuration Errors!
```

python version:
(env_mkdocs) root@web:~/ws/mkdocs# pip show -f python-markdown-math
Name: python-markdown-math
Version: 0.8
Summary: Math extension for Python-Markdown
Home-page: https://github.com/mitya57/python-markdown-math
Author: Dmitry Shachnev
Author-email: mitya57@gmail.com
License: BSD 3-Clause License
Location: /root/ws/mkdocs/env_mkdocs/lib/python3.8/site-packages
Requires: Markdown
Required-by: 
Files:
  __pycache__/mdx_math.cpython-38.pyc
  mdx_math.py
  python_markdown_math-0.8.dist-info/INSTALLER
  python_markdown_math-0.8.dist-info/LICENSE
  python_markdown_math-0.8.dist-info/METADATA
  python_markdown_math-0.8.dist-info/RECORD
  python_markdown_math-0.8.dist-info/WHEEL
  python_markdown_math-0.8.dist-info/entry_points.txt
  python_markdown_math-0.8.dist-info/top_level.txt

**Comment by mitya57** [comment]
> `- mdx_mat # https://github.com/mitya57/python-markdown-math`

You forgot `h` letter.

**Comment by shuivin** [comment]
> 

hah, so stupid  I am!@@
