### ISSUE TITLE
Escaping $ when using `enable_dollar_delimiter`

### ISSUE THREAD

**Issue by a3nm** [mitya57/python-markdown-math#18]
When `enable_dollar_delimiter` is set to True, you cannot use "$" in text. Would it be possible to add a way to escape it, to be able to use it without its delimiter meaning? Using "\$" seems to do only half of the job currently: it disables MathJax, but "\\$" renders as "\\$", not as "$".

**Comment by mitya57** [comment]
Sorry for the delayed response. This should be now fixed in master, can you please test if it works for you?

**Comment by a3nm** [comment]
Sorry for the delay, but yes, I just tested and indeed it works for me. Thanks a lot!

**Comment by mitya57** [comment]
Thanks for the confirmation!
