### ISSUE TITLE
Please list LICENSE in the MANIFEST.in

### ISSUE THREAD

**Issue by eli-schwartz** [mitya57/python-markdown-math#20]
This ensures that PyPI tarballs contain the licensing information, which is important since unlike the GPL, the BSD license contains a unique copyright line and downstream distributors (e.g. Arch Linux) are required to provide the full license text.

**Comment by mitya57** [comment]
Interesting, setuptools has a “smart sdist” which should include all files under revision control in the tarball. So I wonder why it did not include LICENSE.

Anyway, I will now list it explicitly in `MANIFEST.in`.

**Comment by eli-schwartz** [comment]
Hmm, https://github.com/pypa/setuptools/blob/6894478f878b4b579ae8a40e81fa002ad31f63b9/setuptools/command/sdist.py#L24-L25

I'm not sure I understand the docstring at all. Anyway if one wishes to get the files based on what is tracked in revision control, I'm pretty sure "the" way to do this is https://github.com/pypa/setuptools_scm

**Comment by eli-schwartz** [comment]
Thanks, I've uploaded the new package with the LICENSE workaround removed and enabling tests.
