### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by gbishop** [mitya57/python-markdown-math#21]
I'm getting the following messages when I initialize it. It works fine.

/home/gb/.local/lib/python3.6/site-packages/markdown/util.py:453: DeprecationWarning: Using the add method to register a processor or pattern is deprecated. Use the `register` method instead.
  'Use the `register` method instead.', DeprecationWarning
/home/gb/.local/lib/python3.6/site-packages/markdown/core.py:128: DeprecationWarning: The 'md_globals' parameter of 'mdx_math.MathExtension.extendMarkdown' is deprecated.
  ext._extendMarkdown(self)

**Comment by mitya57** [comment]
Fixed in master, thanks!
