### ISSUE TITLE
Formula do not display (in wagtail)

### ISSUE THREAD

**Issue by StefanUlbrich** [mitya57/python-markdown-math#24]
Hi, thanks a lot for the amazing extension!

I tried to integrate mathjax into [a markdown extension for wagtail](https://github.com/torchbox/wagtail-markdown#syntax-highlighting) and I got to a point where formulas appear in the rendered html as 

```html
<script type="math/tex; mode=display"> E = m\cdot c^2 </script>
```

but the formula does not show up. I followed the instructions on the Readme (especially the settings) and `MathJax.Message.Log()` on the console shows only the two loaded extensions. The script tag has a `display=none` property but I have no idea where this can be changed.

**Comment by StefanUlbrich** [comment]
My bad. I put the configuration _after_ the displayed formulas. The extension works just fine.

**Comment by CsatiZoltan** [comment]
@StefanUlbrich Could you show me a complete example on what to write to the HTML file? I wrote `markdown("$$x^2$$", extensions=['mdx_math'])` in Python, which resulted in `<p>\n<script type="math/tex; mode=display">x^2</script>\n</p>`, which is fine. How to proceed?

**Comment by mitya57** [comment]
@CsatiZoltan Did you see the README?

https://github.com/mitya57/python-markdown-math#usage

**Comment by StefanUlbrich** [comment]
Hi .. something along the lines like that (I embedded it into my personal blog):

```html
{% extends "base.html" %}
{% load static wagtailimages_tags wagtailcore_tags %}

{% block extra_css %}
{% comment %} Syntax highlighting in markdown blocks {% endcomment %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/pygments.css' %}">
{% endblock extra_css %}

{% block content %}
<script type="text/x-mathjax-config"> {% comment %} I put this one in the extra CSS which was parsed after the formulas {% endcomment %}
MathJax.Hub.Config({
  config: ["MMLorHTML.js"],
  jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
  extensions: ["MathMenu.js", "MathZoom.js"]
});
</script>
{% block blog_content %}
{% endblock blog_content %}
{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js">
</script>
{% endblock extra_js %}
```

Hope it helps

**Comment by CsatiZoltan** [comment]
@mitya57 Yes, that's what I tried
```
<script type="text/javascript" 

src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js">
</script>

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  config: ["MMLorHTML.js"],
  jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
  extensions: ["MathMenu.js", "MathZoom.js"]
});
</script>

<p>
<script type="math/tex">e^x</script>
</p>
```

Sorry, I am completely new to HTML.

**Comment by CsatiZoltan** [comment]
This question came from [another site](https://github.com/Image-Py/imagepy/issues/78#issuecomment-579287628). I copy the answer here, it may be useful for later newbies:

```
<html lang="en">
<head>
<meta content="text/html; charset=utf-8" http-equiv="content-type" />
</head>

<body>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      config: ["MMLorHTML.js"],
      jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
      extensions: ["MathMenu.js", "MathZoom.js"]
    });
</script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js"></script>

</body>
```

**Comment by mitya57** [comment]
I recommend moving all `<script>` tags to `<head>`, but like this should also work.
