### ISSUE TITLE
python-markdown-math fails to build with Python 3.10.0a2

### ISSUE THREAD

**Issue by jose-matos** [mitya57/python-markdown-math#29]
Hello,
  I am packaging python-markdown-math on Fedora Linux.

In Fedora we testing all packages with python 3.10 (alpha release). While testing the 0.7 release we found a test that fails:
```
======================================================================
FAIL: test_standalone_gitlab (__main__.MathTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-markdown-math-0.7/test.py", line 17, in
<lambda>
    return lambda self: self.verify(mkd_name, html_name, config=config)
  File "/builddir/build/BUILD/python-markdown-math-0.7/test.py", line 14, in
verify
    self.assertEqual(html, md.convert(mkd) + '\n')
AssertionError: '<scr[97 chars]pt>\n\n<script type="math/tex;
mode=display">\[38 chars]t>\n' != '<scr[97 chars]pt>\n<script type="math/tex;
mode=display">\n [36 chars]t>\n'
  <script type="math/tex; mode=display">
   e^{i \varphi} =
   \cos \varphi + i \sin \varphi
  </script>
- 
  <script type="math/tex; mode=display">
   \text{one more math block}
  </script>
```

The original bug report can be found here:
https://bugzilla.redhat.com/show_bug.cgi?id=1900512

This is not urgent since python 3.10 is expected to be released in October.

**Comment by mitya57** [comment]
Hi! I think it is already fixed in python-markdown-math 0.8. Can you please check?

**Comment by jose-matos** [comment]
First: thank you for your prompt reply. :-)

I saw that you already preparing version 0.8.

If you do not mind I will repeat the tests when 0.8 is out. As I told in the original message the purpose of this report was that this issue does not get lost.

**Comment by mitya57** [comment]
0.8 was out on November 3rd:

- https://pypi.org/project/python-markdown-math/0.8/
- https://github.com/mitya57/python-markdown-math/releases/tag/0.8

**Comment by jose-matos** [comment]
Oops. You are right, I have fixed this glaring mistake on my part. I am now following the releases directly.

Looking in to this specific issue I think that you are right.
The test was run against python-markdown 3.3 and thus the 0.8 fixes this issue.
I am closing this issue. If other issues show on I will report them here.
Best regards.
