### ISSUE TITLE
Parsing clash with underscore emphasis

### ISSUE THREAD

**Issue by c42f** [mitya57/python-markdown-math#8]
Hi, thanks for this plugin, and thanks for going to the effort to release it on pypi, it really makes things easier.

I've been using it to write some technical documentation, and have found what seems to be a clash with underscore emphasis.  I haven't had the time to get to the bottom of it yet, so I thought I'd report it here.  Simple test case:

```python
In [3]: import markdown
In [4]: md = markdown.Markdown(extensions=['math'])
In [5]: md.convert(r'${a}_{b}$ ${c}_{d}$')
Out[5]: u'<p>${a}<em>{b}$ ${c}</em>{d}$</p>'
```

Obviously the emphasis tags which have been inserted here across the boundaries of the math notation are bogus...

**Comment by c42f** [comment]
Uh oh, I think this is my fault, I'm missing `enable_dollar_delimiter` in the extension config.  It just so happens that most math renders fine without this, with mathjax configured to parse `$...$` notation.

For anyone else hitting the issue, the appropriate mkdocs configuration section looks like
```yml
markdown_extensions:
    - math:
        enable_dollar_delimiter: True
```

**Comment by mitya57** [comment]
Right. I also suggest to disable the `tex2jax` extension of MathJax because it has some potential conflicts with this extension (i.e. it can try processing escaped delimiters that this extension did not handle).

**Comment by c42f** [comment]
Thanks!
