### ISSUE TITLE
'enable_dollar_delimiter' is mandatory

### ISSUE THREAD

**Issue by videlec** [mitya57/python-markdown-math#9]
I tried to use the math extension but it ended up with

    /usr/local/lib/python2.7/dist-packages/mdx_math.pyc in extendMarkdown(self, md, md_globals)
         45             markdown.inlinepatterns.Pattern(r'(?<!\\)(\\begin{([a-z]+?\*?)})(.+?)(\\end{\3})')
         46         )
    ---> 47         if not configs['enable_dollar_delimiter']:
         48             inlinemathpatterns = inlinemathpatterns[1:]
         49         for i, pattern in enumerate(inlinemathpatterns):
    
    KeyError: 'enable_dollar_delimiter'

I guess that a configs.get('enable_dollar_delimiter') would be safer.

**Comment by videlec** [comment]
I installed via pip... it seems that in the github version it uses the safer getConfig! I will try it out.

**Comment by mitya57** [comment]
I have just uploaded the latest git version to PyPI (released as 0.2). This should resolve your issue.
